name: metalheadd
description: "A professional sports profile and match tracking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  # State Management
  flutter_riverpod: ^2.5.1

  # UI and Styling
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  # Data Formatting (Dates/Currency)
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Including the directory includes all files inside it
    - assets/images/
    - assets/fonts/

  # Example of how to add custom fonts if you have them in assets/fonts/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700